-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE user_role AS ENUM ('admin', 'manager', 'client');
CREATE TYPE ticket_status AS ENUM ('new', 'in_work', 'have_unread', 'ready', 'next_department');
CREATE TYPE msg_status AS ENUM ('draft', 'sent', 'read');

CREATE TABLE users (
    uuid TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    login CITEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role user_role NOT NULL,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_login_not_blank_chk CHECK (btrim(login::TEXT) <> ''),
    CONSTRAINT users_password_not_blank_chk CHECK (btrim(password) <> '')
);

CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL UNIQUE,
    default_dep BOOLEAN NOT NULL DEFAULT FALSE,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT departments_name_not_blank_chk CHECK (btrim(name::TEXT) <> '')
);

CREATE TABLE clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid TEXT NOT NULL UNIQUE REFERENCES users (uuid) ON DELETE CASCADE,
    info JSONB NOT NULL DEFAULT '{}'::JSONB,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clients_info_object_chk CHECK (jsonb_typeof(info) = 'object')
);

CREATE TABLE managers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES departments (id) ON DELETE RESTRICT,
    user_uuid TEXT NOT NULL UNIQUE REFERENCES users (uuid) ON DELETE CASCADE,
    name TEXT NOT NULL,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT managers_name_not_blank_chk CHECK (btrim(name) <> '')
);

CREATE TABLE schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES departments (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    work_from TIMESTAMPTZ NOT NULL,
    work_to TIMESTAMPTZ NOT NULL,
    break_from TIMESTAMPTZ NOT NULL,
    break_to TIMESTAMPTZ NOT NULL,
    is_week_end BOOLEAN NOT NULL DEFAULT FALSE,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT schedules_name_not_blank_chk CHECK (btrim(name) <> ''),
    CONSTRAINT schedules_work_window_chk CHECK (work_from < work_to),
    CONSTRAINT schedules_break_window_chk CHECK (break_from < break_to),
    CONSTRAINT schedules_break_inside_work_chk CHECK (break_from >= work_from AND break_to <= work_to),
    CONSTRAINT schedules_single_day_chk CHECK (
        date_trunc('day', work_from) = date_trunc('day', work_to)
        AND date_trunc('day', work_from) = date_trunc('day', break_from)
        AND date_trunc('day', work_from) = date_trunc('day', break_to)
    )
);

ALTER TABLE schedules
    ADD CONSTRAINT schedules_non_overlapping_per_department_excl
    EXCLUDE USING GIST (
        department_id WITH =,
        tstzrange(work_from, work_to, '[)') WITH &&
    );

CREATE TABLE tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER REFERENCES departments (id) ON DELETE SET NULL,
    name TEXT NOT NULL DEFAULT '',
    manager_user_uuid TEXT REFERENCES managers (user_uuid) ON DELETE SET NULL,
    client_user_uuid TEXT NOT NULL REFERENCES clients (user_uuid) ON DELETE RESTRICT,
    status ticket_status NOT NULL DEFAULT 'new',
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tickets_distinct_participants_chk CHECK (
        manager_user_uuid IS NULL OR manager_user_uuid <> client_user_uuid
    )
);

CREATE TABLE messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    user_uuid TEXT NOT NULL REFERENCES users (uuid) ON DELETE RESTRICT,
    text BYTEA NOT NULL,
    status msg_status NOT NULL DEFAULT 'sent',
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT messages_text_not_empty_chk CHECK (octet_length(text) > 0)
);

CREATE TABLE message_files (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg_id INTEGER NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    path TEXT NOT NULL UNIQUE,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT message_files_name_not_blank_chk CHECK (btrim(file_name) <> ''),
    CONSTRAINT message_files_path_not_blank_chk CHECK (btrim(path) <> '')
);

CREATE TABLE refresh_tokens (
    jti UUID PRIMARY KEY,
    user_uuid TEXT NOT NULL UNIQUE REFERENCES users (uuid) ON DELETE CASCADE,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '30 days'),
    CONSTRAINT refresh_tokens_expires_after_create_chk CHECK (expires_at > create_at)
);

CREATE INDEX schedules_department_work_from_idx
    ON schedules (department_id, work_from, work_to);

CREATE INDEX tickets_client_user_uuid_hash_idx
    ON tickets USING HASH (client_user_uuid);

CREATE INDEX tickets_manager_user_uuid_hash_idx
    ON tickets USING HASH (manager_user_uuid)
    WHERE manager_user_uuid IS NOT NULL;

CREATE INDEX tickets_department_status_update_at_idx
    ON tickets (department_id, status, update_at DESC);

CREATE INDEX messages_ticket_create_at_idx
    ON messages (ticket_id, create_at DESC, id DESC);

CREATE INDEX messages_unread_user_uuid_create_at_idx
    ON messages (user_uuid, create_at DESC, id DESC)
    WHERE status = 'sent';

CREATE INDEX message_files_msg_id_idx
    ON message_files (msg_id);

CREATE INDEX refresh_tokens_expires_at_idx
    ON refresh_tokens (expires_at);

CREATE UNIQUE INDEX departments_single_default_dep_idx
    ON departments (default_dep)
    WHERE default_dep;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_update_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.update_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_department_default_dep()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.default_dep = NOT EXISTS (SELECT 1 FROM departments);
        RETURN NEW;
    END IF;

    IF NEW.default_dep AND NEW.default_dep IS DISTINCT FROM OLD.default_dep THEN
        UPDATE departments
        SET default_dep = FALSE
        WHERE id <> NEW.id
          AND default_dep;
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION protect_default_department_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.default_dep THEN
        RAISE EXCEPTION 'default department % cannot be deleted', OLD.id
            USING ERRCODE = '23514';
    END IF;

    RETURN OLD;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION assert_user_role()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    actual_role user_role;
BEGIN
    SELECT u.role
    INTO actual_role
    FROM users AS u
    WHERE u.uuid = NEW.user_uuid;

    IF actual_role IS NULL THEN
        RAISE EXCEPTION 'user % does not exist', NEW.user_uuid
            USING ERRCODE = '23503';
    END IF;

    IF actual_role::TEXT <> TG_ARGV[0] THEN
        RAISE EXCEPTION 'user % must have role %, got %', NEW.user_uuid, TG_ARGV[0], actual_role
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION protect_user_role_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.role = OLD.role THEN
        RETURN NEW;
    END IF;

    IF EXISTS (SELECT 1 FROM managers WHERE user_uuid = NEW.uuid)
       AND NEW.role <> 'manager' THEN
        RAISE EXCEPTION 'user % has manager profile and cannot switch to role %', NEW.uuid, NEW.role
            USING ERRCODE = '23514';
    END IF;

    IF EXISTS (SELECT 1 FROM clients WHERE user_uuid = NEW.uuid)
       AND NEW.role <> 'client' THEN
        RAISE EXCEPTION 'user % has client profile and cannot switch to role %', NEW.uuid, NEW.role
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION validate_ticket_manager_department()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    manager_department_id INTEGER;
BEGIN
    IF NEW.manager_user_uuid IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.department_id IS NULL THEN
        RAISE EXCEPTION 'department_id is required when manager_user_uuid is set'
            USING ERRCODE = '23514';
    END IF;

    SELECT m.department_id
    INTO manager_department_id
    FROM managers AS m
    WHERE m.user_uuid = NEW.manager_user_uuid;

    IF manager_department_id IS NULL THEN
        RAISE EXCEPTION 'manager % does not exist', NEW.manager_user_uuid
            USING ERRCODE = '23503';
    END IF;

    IF manager_department_id <> NEW.department_id THEN
        RAISE EXCEPTION 'manager % belongs to department %, ticket department is %',
            NEW.manager_user_uuid, manager_department_id, NEW.department_id
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION touch_ticket_update_at_from_message()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tickets
    SET update_at = CURRENT_TIMESTAMP
    WHERE id = NEW.ticket_id;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION purge_expired_refresh_tokens()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    WITH deleted AS (
        DELETE FROM refresh_tokens
        WHERE expires_at <= CURRENT_TIMESTAMP
        RETURNING 1
    )
    SELECT COUNT(*)
    INTO deleted_count
    FROM deleted;

    RETURN deleted_count;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION cleanup_expired_refresh_tokens_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM purge_expired_refresh_tokens();

    IF NEW.expires_at <= CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION 'refresh token expires_at must be in the future'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER users_set_update_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_update_at();

CREATE TRIGGER departments_set_update_at
    BEFORE UPDATE ON departments
    FOR EACH ROW
    EXECUTE FUNCTION set_update_at();

CREATE TRIGGER departments_set_default_dep
    BEFORE INSERT OR UPDATE OF default_dep ON departments
    FOR EACH ROW
    EXECUTE FUNCTION set_department_default_dep();

CREATE TRIGGER departments_protect_default_delete
    BEFORE DELETE ON departments
    FOR EACH ROW
    EXECUTE FUNCTION protect_default_department_delete();

CREATE TRIGGER managers_set_update_at
    BEFORE UPDATE ON managers
    FOR EACH ROW
    EXECUTE FUNCTION set_update_at();

CREATE TRIGGER schedules_set_update_at
    BEFORE UPDATE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION set_update_at();

CREATE TRIGGER tickets_set_update_at
    BEFORE UPDATE ON tickets
    FOR EACH ROW
    EXECUTE FUNCTION set_update_at();

CREATE TRIGGER managers_assert_user_role
    BEFORE INSERT OR UPDATE OF user_uuid ON managers
    FOR EACH ROW
    EXECUTE FUNCTION assert_user_role('manager');

CREATE TRIGGER clients_assert_user_role
    BEFORE INSERT OR UPDATE OF user_uuid ON clients
    FOR EACH ROW
    EXECUTE FUNCTION assert_user_role('client');

CREATE TRIGGER users_protect_role_change
    BEFORE UPDATE OF role ON users
    FOR EACH ROW
    EXECUTE FUNCTION protect_user_role_change();

CREATE TRIGGER tickets_validate_manager_department
    BEFORE INSERT OR UPDATE OF manager_user_uuid, department_id ON tickets
    FOR EACH ROW
    EXECUTE FUNCTION validate_ticket_manager_department();

CREATE TRIGGER messages_touch_ticket_update_at
    AFTER INSERT OR UPDATE OF status ON messages
    FOR EACH ROW
    EXECUTE FUNCTION touch_ticket_update_at_from_message();

CREATE TRIGGER refresh_tokens_cleanup_expired
    BEFORE INSERT OR UPDATE ON refresh_tokens
    FOR EACH ROW
    EXECUTE FUNCTION cleanup_expired_refresh_tokens_trigger();

-- +goose Down
DROP TRIGGER IF EXISTS refresh_tokens_cleanup_expired ON refresh_tokens;
DROP TRIGGER IF EXISTS messages_touch_ticket_update_at ON messages;
DROP TRIGGER IF EXISTS tickets_validate_manager_department ON tickets;
DROP TRIGGER IF EXISTS users_protect_role_change ON users;
DROP TRIGGER IF EXISTS clients_assert_user_role ON clients;
DROP TRIGGER IF EXISTS managers_assert_user_role ON managers;
DROP TRIGGER IF EXISTS tickets_set_update_at ON tickets;
DROP TRIGGER IF EXISTS schedules_set_update_at ON schedules;
DROP TRIGGER IF EXISTS managers_set_update_at ON managers;
DROP TRIGGER IF EXISTS departments_protect_default_delete ON departments;
DROP TRIGGER IF EXISTS departments_set_default_dep ON departments;
DROP TRIGGER IF EXISTS departments_set_update_at ON departments;
DROP TRIGGER IF EXISTS users_set_update_at ON users;

DROP INDEX IF EXISTS departments_single_default_dep_idx;

DROP FUNCTION IF EXISTS cleanup_expired_refresh_tokens_trigger();
DROP FUNCTION IF EXISTS purge_expired_refresh_tokens();
DROP FUNCTION IF EXISTS touch_ticket_update_at_from_message();
DROP FUNCTION IF EXISTS validate_ticket_manager_department();
DROP FUNCTION IF EXISTS protect_user_role_change();
DROP FUNCTION IF EXISTS assert_user_role();
DROP FUNCTION IF EXISTS protect_default_department_delete();
DROP FUNCTION IF EXISTS set_department_default_dep();
DROP FUNCTION IF EXISTS set_update_at();

DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS message_files;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS managers;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS msg_status;
DROP TYPE IF EXISTS ticket_status;
DROP TYPE IF EXISTS user_role;
